### PR TITLE
AHT10 temperature/humidity sensor

### PR DESCRIPTION
**Pull request by KooLru**
AHT10 temperature/humidity sensor implementation based on HTU21D implementation and https://github.com/enjoyneering/AHT10 library.

Product overview 
AHT10, the new generation of temperature and humidity sensors sets a new standard in size and intelligence: it is embedded for reflow soldering 
The dual-row flat leadless SMD package has a 4x5mm bottom and a height of 1.6mm. 
The sensor outputs a calibrated digital signal in standard I2C format. 
The AHT10 is equipped with a newly designed ASIC- specific chip, an improved MEMS semiconductor capacitive humidity sensing element and a standard on-chip temperature sensing element. Its performance has been greatly improved beyond the reliability level of the previous generation of sensors. The first generation of temperature and humidity sensors have been improved to make them more stable in harsh environments. 
Each sensor is calibrated and tested with a product lot number printed on the surface of the product. Thanks to improved and miniaturized sensors, it is more cost-effective and ultimately all equipment will benefit from cutting-edge energy-saving operating modes.

### CODE REVIEW

**Comment by user2684** [comment]
Good to me, merging it, thanks! Looks like there is a compilation error in the automatic checks but seems to be unrelated to your changes.

**Comment by user2684** [comment]
Apologize, just realized it was missing, would you mind adding to `.github/workflows/test.yml` a section for this new sensor just above the "Compile all test cases" job? Let me know of course if you need any assistance with it. Thanks!

**Comment by KooLru** [comment]
I add test case section and install AHT10 library section.

**Comment by user2684** [comment]
Good to me thanks a lot! Merging

**Pull request merged**
