### PR TITLE
Added TMP102 temperature sensor

### PR DESCRIPTION
**Pull request by mtiutiu**

### CODE REVIEW

**Comment by mtiutiu** [comment]
Seems that the **original AM2320 library** used in this project has an issue and that's why its corresponding automated tests keep failing. I opened a PR for it [here](https://github.com/thakshak/AM2320/pull/9).

**Comment by mtiutiu** [comment]
Tested on real hardware and I can confirm that it works as expected.

**Comment by user2684** [comment]
Thanks for the contribution! Let me run just a couple of tests and I'll merge it straight away!

**Comment by user2684** [comment]
Hi, just a couple of asks before merging it: 
- Would you mind adding custom functions (e.g. setConversionRate() and setExtended()) to the README file as well, jut below other sensors'?
- Thanks for submitting the PR for the AM2320 issue. Would you mind commenting out the travis lines for AM2320 so we can have a clean compilation for all the sensors? So once merged also other pending PRs can be aligned. We will then uncomment it back once they will fix it but at least in the way developers can understand if they have a failure or not
Thanks!

**Comment by mtiutiu** [comment]
@user2684 Done.

**Comment by user2684** [comment]
Oh finally I clean compilation, many thanks for the contribution! Just merged

**Pull request merged**
