### PR TITLE
Architecture Review

### LINKED ISSUE #132: Provide remote logging
Wrapping Serial.print() and sending out a message for every log entry when an option is enabled

### LINKED ISSUE #180: Improve debug output
* prepend millis() 
* prepend a static string (e.g. NM)

### LINKED ISSUE #243: Split between reporting and taking a measurement
https://forum.mysensors.org/topic/6534/nodemanager/138

> I'm trying to implement an OLED display, where the node would wake up every 5 seconds, take a measurement and display it on the OLED. But the report interval to the MySensors gateway should only be 10 minutes. I thought that
> node.setSleepSeconds(5); node.setReportIntervalMinutes(10); would be the correct way to setup NodeManager to take measurements every 5 seconds, but only report it every 10 minutes to the network. Unfortunately, Sensor::loop(MyMessage* message) seems to immediately return without measurement if the reporting timer has not elapsed. Somehow I don't understand that logic. Why have different sleep and reporting intervals when measurements will only be taken at reporting intervals anyway? I would expect measurements to be taken with the sleep intervals (e.g. to calculate an average over the whole reporting interval) and report back to the network using report intervals

### LINKED ISSUE #303: Ability to provide messages through Serial input for debugging purposes

### LINKED ISSUE #304: Allow SensorPulseMeter and subclasses to persist counters in EEPROM

### LINKED ISSUE #323: For debug output, use the same approach of MySensors library
with preprocessor directives instead of using Serial.print() directly.
DEBUG_OUTPUT() calls void hwDebugPrint(const char *fmt, ... );

### LINKED ISSUE #352: For interrupt-based sensor add global option to verify value
if ( (_interrupt_mode == RISING && value == HIGH ) || (_interrupt_mode == FALLING && value == LOW) || (_interrupt_mode == CHANGE) )  {

### LINKED ISSUE #353: RTC: add option to customize how often to sync with controller

### LINKED ISSUE #361: PowerManager should be turned on also during setup()
Otherwise some sensors cannot be initialized correctly

### LINKED ISSUE #367: Make LCD display object accessible in Display class and subclasses
In this way if hooking onLoop() users have full control of the display

### LINKED ISSUE #368: Add option to store the time in the local timezone

### LINKED ISSUE #394: Add ability to report at a configured minute of the hour
can be useful for SensorPulseMeter and such

### LINKED ISSUE #403: Timer fails to honor a value of more than one day
Because using signed int for keeping track of the value

### LINKED ISSUE #404: Timer elapsed time not accurate
Timer::update() doesn't get called under certain conditions (e.g. an interrupt takes place) so making the counter not always accurate (especially for a sleeping node)

### LINKED ISSUE #405: sleepBetweenSend causes ack retries
> For Battery Powered Sensor, the major point is sleepBetweenSend() method. In fact I have some issue with.
> But the first question is: What is the purpose of this function ? My feeling is that can help, and that help, getting the radio capacitor back after a send. But pushing the sensor in sleep mode will produce Ack answer errors in case of messages requiring Ack (example presentation) and the sensor will retry. Finally the sensor use more power.

### PR DESCRIPTION
**Pull request by user2684**
This PR reviews the architecture of NodeManager.

NodeManager files structure:
* New Arduino-compatible library structure to allow easier integration, more consistent upgrades across version, and a complete set of examples.
* The code of each sensor is now in a dedicated header file under the `sensors` directory which can be directly included by the user when needed. Implementation of the class is _inline_. Required libraries and OTA configuration request handling is now centralized inside the class. This approach should facilitate integration of new sensors (also because can be developed in parallel) and centralize all the sensor-related tasks
* Split NodeManager's core classes in individual files
* Moved v1.7 main sketch into `examples/Template` and examples from the README file into individual sketches in  `examples`
* Added `keywords.txt` file with NodeManager's capabilities defined as LITERAL1, NodeManager classes and sensors as KEYWORD1 and NodeManager functions as KEYWORD2. Sensor specific functions are not supposed to be defined here
* Added Travis CI additional tests covering all the capabilities, the sensors, the examples and previous versions of the MySensors library

NodeManager core capabilities:
* No more the need to create a NodeManager instance in the sketch. An global object called `nodeManager` is now created as extern in within the library. This also simplify the code since there is no more the need to pass its reference throughout the code and save some more memory 
* Deprecated the `USE_*` defines since now the user can import a sensor directly from the sketch, just before invoking the constructor (e.g. `#include <sensors/SensorBattery.h>`)
* Renamed `FEATURE_*` into `NODEMANAGER_*` (e.g. `FEATURE_DEBUG` is now `NODEMANAGER_DEBUG`). This is because being a library we need to have our variables somehow linked to it
* Added `NODEMANAGER_OTA_CONFIGURATION` configuration setting, OFF by default, when ON, enables OTA configuration. There is no more the need to create an instance of `SensorConfiguration` since done automatically within the code when `NODEMANAGER_OTA_CONFIGURATION` is ON
* Added `NODEMANAGER_SERIAL_INPUT` default to OFF; which allows reading from the serial port at the end of each loop cycle expecting command formatted according to the MySensors serial protocol. Useful for debugging interactive sensors such as relays without the need to send messages over the network (fixes #303) 
* Added `NODEMANAGER_DEBUG_VERBOSE`, default to OFF, so to allow saving additional memory by moving heavy debug output like those in LOG:MSG into this mode
* When `NODEMANAGER_POWER_MANAGER` is `ON`, `powerOn()` and `powerOff()` are also called during `NodeManager` and `Sensor` setup() (fixes #361)
* Added `debug()` macro which is using MySensors' `hwDebugPrint()` resulting in a better compatibility, more readable and concise code (fixes #323 #373)
* Debug output is now fully compatible with the one used by the MySensors library (fixes #180). Documentation and regexp are provided below and the code has been already integrated into LogParser (https://www.mysensors.org/build/parser)
* Added support for OTA debug by leveraging MySensors library functionality and added commented defines in the sketch template (fixes #132)
* ` sleepBetweenSend()` call `wait()` and no more `sleep()` to avoid retries with Ack messages (fixes #405)

NodeManager API:
* Added `NodeManager::setTimezone()` to set the hour offset to be applied for when received a UTC timestamp from the controller (fixes #368) 
* Added `setSyncTimeOnSetup()`, `setSyncTimeAfterSleep()` and `setSyncTimeAfterInterval()` to the NodeManager class to better control how often, if and when to sync the time with the controller, especially when the user wants to rely on a RTC (for this reason time with the RTC if configured is always synchronized regardless of these settings) (fixes #353) 

Sensor API:
* Added a Measure Timer so to allow splitting between taking measures and reporting. If not set explicitly, will be automatically set as the reporting timer so to align measures and reporting (fixes #243 #398 )
* The new Timer's options can be accessed by the user with the new Sensor's methods `setReportTimerMode()`, `setReportTimerValue()`, `setMeasureTimerMode()` and `setMeasureTimerValue()`. Other functions like `setReportInterval*()` have been kept for compatibility and simply calls `setReportTimerMode(TIME_INTERVAL)` and `setReportTimerValue(seconds)`
* Added `Sensor::onOTAConfiguration(ConfigurationRequest* request)` which can be implemented by each sensor to support OTA configuration requests
* Implemented a default `Sensor::onReceive(MyMessage* message)` since the same code was used for most of the sensors which can be still overridden by each sensor. When a child receive a REQ message and the type matches the type of the request, executes its onLoop function. Removed `onReceive()` from all the sensors using the default logic
* Added `setInterruptStrict()` to `Sensor`. When true (the default), the value of the pin is checked and the interrupt ignored if RISING and not HIGH or FALLING and not LOW (fixes #352)
* Moved `setInitialValue()` (renamed into `setPinInitialValue()`), `setInterruptMode()`, `setWaitAfterInterrupt()` from `SensorInterrupt `and `SensorPulseMeter` into `Sensor` and their logic into `Sensor::setup()` so that present and future interrupt-based sensors can use them
* Deprecated `SensorInterrupt::setArmed()` since can be emulated by the new Timer class
* Deprecated `Sensor::onBefore()` since no sensors was using it so to save additional storage. Debug output is no more printing the registration of the sensors since redundant with the presentation in the network
* Added `getDisplay()` method to `Display` subclasses so the user can have access to the LCD object for advanced configurations if needed (fixes #367)

Child API:
* Deprecated Child subclasses `ChildInt`, `ChildFloat`, `ChildDouble` and `ChildString`. All the required conversion now happens transparently within the Child class which takes as an additional parameter the value format (INT, FLOAT, DOUBLE, STRING). This simplify the code (avoid casting Child to the right subclass for every sensor) and save an additional 500+ bytes of storage.
* `Child::setValue()` now prints out the value just set, together with the child description and id. In this way there is no more the need to have a manual debug output for each sensor
* Child (apart from STRING format) support keeping track of the last value assigned in EEPROM and restoring it upon a reboot when `NODEMANAGER_EEPROM` is ON  and `setPersistValue()` is set to true. Particularly useful when e.g. the sensor is counting and a power outage takes place or for restoring the last value set to a relay. Enabled by default on `SensorPulseMeter` and subclasses (fixes #304) and in SensorDigitalOutput and subclasses
* Added `setValueProcessing()` to `Child` to configure the behavior of the child when setValue() is called multiple times. It can be NONE (ignore the previous values but the last one),  AVG (averages the values), SUM (sum up the values) (default: AVG). Adapted SensorPulseMeter and its subclasses to use `setValueProcessing(SUM)` and output class to use `setValueProcessing(NONE)`
* Child's last value can be now accessed by other sensors or hook function through `getLastValueInt()`, 
`getLastValueFloat()`, `getLastValueDouble()`, `getLastValueString()`, provided NODEMANAGER_CONDITIONAL_REPORT is set to ON
* Added `setSendWithoutValue()` which allow to send the value to the gateway even if no samples have been collected. Useful for sensors like Rain Gauge which has to report anyway at the end of the cycle
* Renamed Child's `setValue*()` and in just `setValue()`

Timer class:
* Completely reviewed and optimized the Timer class. A timer can now be configured in different way through `setMode()` which sets the way the timer operates. It can be either `TIME_INTERVAL `(e.g. report every X seconds with the amount of time set with `setValue()`), `IMMEDIATELY` (e.g. report at every cycle, useful for sensors like actuators which should report as soon as the value has changed), `DO_NOT_REPORT` (e.g. never report, useful for when there is no need to report, like a Display) and when `FEATURE_TIME `is `ON`, `EVERY_MINUTE/EVERY_HOUR/EVERY_DAY` (e.g. to report the value set in the previous timeframe, useful for sensors reporting an accumulated value linked to a timeframe at regular intervals), `AT_MINUTE/AT_HOUR/AT_DAY `(e.g. report at a given minute/hour/day, useful if the measure is expected at a specified time, set with `setValue()`) (fixes #394 #357)
* Now Timer stores the provided value as unsigned long and no more as signed int so allowing long timeframe to be honored correctly (fixes #403)
* Timer's `update()` is no more called by Sensor but when a timer is created it registers itself against the NodeManager class which is responsible to call it on each register timer (fixes #404)

Other changes:
* Renamed `Request` class into `ConfigurationRequest `since used only by `SensorConfiguration`
* `ConfigurationRequest` now support string input (can be useful for Display class and subclasses)
* Data type refactoring to save additional storage

**_Including NodeManager's library in your projects_**

To make use of the library version, replace in the main sketch:
* `#include "NodeManagerLibrary.h"`
with:
* `#include <MySensors_NodeManager.h>`
This makes (on purpose, to avoid conflicts) NodeManager's v1.7 and v1.8 not compatible

**_Using both measure and report timer_**

The following will configure the sensor to take a measure every 10 seconds and report (the calculated average) every 30 seconds
```c
  battery.setReportIntervalSeconds(30);
  battery.setMeasureTimerMode(TIME_INTERVAL);
  battery.setMeasureTimerValue(10);
```
The following will allow a sensor to take a measure every minute so to be printed on a LCD display but reporting to the network every 5 minutes. Since DisplaySSD1306 calls setReportTimerMode(DO_NOT_REPORT), the screen will be updated at the configured interval:

```c
// temperature will be measured every 60 seconds
  sht21.setMeasureTimerMode(TIME_INTERVAL);
  sht21.setMeasureTimerValue(60);
// temperature will be reported to the network every 5 minutes
  sht21.setReportIntervalMinutes(5);

// the display will "measure" (e.g. run its onLoop) every 60 seconds. Reporting timer is already set to DO_NOT_REPORT
  ssd1306.setMeasureTimerMode(TIME_INTERVAL);
  ssd1306.setMeasureTimerValue(60);
```
 
**_Log Parser Integration_**

The following regexp can be used to make Log Parser understanding NodeManager's debug output:
```js
{ re: "NM:INIT:VER=(.*)", d: "NodeManager version <b>$1</b>" },
{ re: "NM:INIT:INO=(.*)", d: "Sketch <b>$1</b>" },
{ re: "NM:INIT:LIB VER=(.+) CP=(.+)", d: "MySensors Library version <b>$1</b>, capabilities <b>$2</b>" },
{ re: "NM:INIT:RBT p=(\\d+)", d: "Configured reboot pin <b>$1</b>" },
{ re: "NM:BFR:INIT", d: "Connecting to the gateway..." },
{ re: "NM:BFR:OK", d: "Connection to the gateway successful" },
{ re: "NM:BFR:INT p=(\\d+) m=(\\d+)", d: "Setting up interrupt on pin <b>$1</b> with mode <b>$2</b>" },
{ re: "NM:PRES:(\\w+)\\((\\d+)\\) p=(\\d+) t=(\\d+)", d: "Presented to the gateway <b>child $2</b> for sensor <b>$1</b> as <b>{type:0:$3}</b> with type <b>{type:1:$4}</b>" },
{ re: "NM:STP:ID=(\\d+) M=(\\d+)", d: "This node has id <b>$1</b> and metric is set to <b>$2</b>" },
{ re: "NM:STP:SD T=(\\d+)", d: "Connected SD card reader, type <b>$1</b>" },
{ re: "NM:LOOP:(\\w+)\\((\\d+)\\):SET t=(\\d+) v=(.+)", d: "New value for <b>child $2</b> of sensor <b>$1</b> with <b>{type:1:$3}</b> = <b>$4</b>" },
{ re: "NM:LOOP:INT p=(\\d+) v=(\\d+)", d: "Interrupt received on pin <b>$1</b>, value <b>$2</b>" },
{ re: "NM:LOOP:INPUT\\.\\.\\.", d: "Waiting for input from the serial port" },
{ re: "NM:LOOP:INPUT v=(.*)", d: "Received an input from the serial port: <b>$1</b>" },
{ re: "NM:TIME:REQ", d: "Requesting the time to the controller" },
{ re: "NM:TIME:OK ts=(\\d+)", d: "Received the time from the controller: <b>$1</b>" },
{ re: "NM:SLP:WKP", d: "Wakeup requested" },
{ re: "NM:SLP:SLEEP s=(\\d+)", d: "Going to sleep for <b>$1</b> seconds" },
{ re: "NM:SLP:AWAKE", d: "Waking up from sleep" },
{ re: "NM:SLP:LOAD s=(\\d+)", d: "Loaded configured sleep time: <b>$1</b> seconds" },
{ re: "NM:MSG:SEND\\((\\d+)\\) t=(\\d+) p=(.+)", d: "<b>Child $1</b> sent <b>{type:1:$2}</b> = <b>$3</b>" },
{ re: "NM:MSG:RECV\\((\\d+)\\) c=(\\d+) t=(\\d+) p=(.+)", d: "Received a <b>{command:$2}</b> message for <b>child $1</b> with <b>{type:$2:$3}</b> = <b>$4</b>" },
{ re: "NM:PWR:RBT", d: "Rebooting the node as requested" },
{ re: "NM:PWR:ON p=(\\d+)", d: "Powering <b>on</b> the sensor(s) through pin <b>$1</b>" },
{ re: "NM:PWR:OFF p=(\\d+)", d: "Powering <b>off</b> the sensor(s) through pin <b>$1</b>" },
{ re: "NM:OTA:REQ f=(\\d+) v=(\\d+)", d: "Over-the-air configuration change requested, function <b>$1</b> value <b>$2</b>" },
{ re: "NM:EEPR:CLR", d: "Clearing the EEPROM as requested" },
{ re: "NM:EEPR:LOAD i=(\\d+) v=(\\d+)", d: "Read from EEPROM at position <b>$1</b> the value <b>$2</b>" },
{ re: "NM:EEPR:SAVE i=(\\d+) v=(\\d+)", d: "Wrote to EEPROM at position <b>$1</b> the value <b>$2</b>" },
{ re: "NM:EEPR:(\\w+)\\((\\d+)\\):LOAD", d: "Restoring from EEPROM the value of <b>child $2</b> of sensor <b>$1</b>" },
{ re: "NM:EEPR:(\\w+)\\((\\d+)\\):SAVE", d: "Saving to EEPROM the value of <b>child $2</b> of sensor <b>$1</b" },
{ re: "NM:SENS:([^:]+):(.+)", d: "Sensor <b>$1</b>: $2" },
{ re: "!NM:SENS:([^:]+):(.+)", d: "Error in sensor <b>$1</b>: <b style='color:red'>$2</b>" },
```
[NM_Log Parser Tester.zip](https://github.com/mysensors/NodeManager/files/2245955/NM_Log.Parser.Tester.zip)

### CODE REVIEW

**Comment by Akubi** [comment]
Hi,
Great improvement. I'm actually on release 1.7 and plan to move to 1.8-dev, but it's probably better to wait new architecture. Do you have a plan for first dev-release ?
Or can I start tests on the PR version ?
Thank

**Comment by Akubi** [comment]
Perfect thank.
I download the PR and start migrating the testing

**Comment by user2684** [comment]
Thanks! A good starting point could be the updated README file and of course the summary above

**Comment by Akubi** [comment]
Hi, 
I started testing the new architecture.
Again, good job. Is in the good direction.
First test with simple sketch, no special problem.
After that I start porting one of my Custom Sensors.

It take me some time to understand the report and sleep concept. But is now working.

A problem I had, is with EEPROM persistence.
My Custom Sensor is derived from SensorDigitalOutput and I set #define NODEMANAGER_EEPROM ON
No way to have a correct state after node restart.
I believe that the problem is in Child::sendValue(bool force) method.
After sending value a reset() is called. The reset clear the total, reset the sample count, ok, but also the value.
Not sure this is a good idea, we are unable to check actual value in the sketch if needed. But the real problem is that reset() method after clearing the value send the cleared value to the EEPROM. So EEPROM is always 0 after à send. For me the goal was to recover the DigitalOutputafter a recover from power fail. Maybe your idea was different.

Second problem is using NODEMANAGER_CONDITIONAL_REPORT.
Suppose you have a _value_delta of 5 and your value increase of 1 at each loop.
The  Child::sendValue(bool force) method don’t send the value because delta not is reached and then do _last_value = _value;
So at next loop delta still =1 and we never send data. I believe you only have to keep track of the previous value if value is send.

Please let me know if you agree with my remarks.

I will now test some battery powered sketch and check the NODEMANAGER_POWER_MANAGER and low power capability.

**Comment by user2684** [comment]
Thanks again for running these tests! The problem with the EEPROM, got it, there is for sure something to review there. I'll run a few tests and see how to fix it. Regarding conditional reporting, actually the code has not changed but probably had issues since the beginning and your logic sounds much more reasonable then the current one which is implemented. I'll let you know once an updated version is pushed here, meanwhile I will hold on from merging. Thanks!

**Comment by Akubi** [comment]
Thank for your answer.
On EEPROM the first question is : Do you want to keep compatibility with previews version or not. If yes a simple modification in reset() function can solve the problem, if not required, I can propose you a « more efficient way to save data ». My opinion, up to you to select the way.

Actually I’m testing a node with battery and htu21 sensor. The module use NFR24, run at 1MHz and is powered with a CR2032.

First test are ok. I will get you some feedback after a some test.

**Comment by davidgladstone** [comment]
I concur with the CONDITIONAL_REPORT issue mentioned above. I just fixed this in the same way in my 1.7 codebase this morning prior to reading this.

**Comment by Akubi** [comment]
Hi,

Testing the Battery powered sensor, I face a big problem with timers.
Timers are not working as intended.
I prepared and tested a different way to manage timers in order to solve the problem.
So my question is, how can I send you a revised code ?
I can attach explanations in this discussion or maybe create a PR in your( @user2684) NodeManager “_feature/architecture_review_” branch.
What do you prefer ?

**Comment by Akubi** [comment]
OK perfect,

I will try to prepare this evening a description, explanation and kind of diff report for the timer issue.

For the EEPROM and CONDITIONAL_REPORT I will work on it next week. I report a proposal as soon as possible.

Of course @davidgladstone, please submit your proposal also, so we can share/compare/merge.

**Comment by Akubi** [comment]
First of all, a short introduction on the issue.

I setup a battery powered node with 2 sensors and sleep mode enabled:
•	BatterySensor
•	HTu21d sensor

First test was done with:
•	nodemanager.setreporttimesecons(10)
•	nodemanager.sleep(10)
•	battery report(10)

All was ok.

Finaly I released a node with 
•	nodemanager.setreporttimeMinutes(10)
•	nodemanager.sleepminutes(10)
•	battery reportheures(6)

What I notice on the released sensor is that after 2 days no battery information was send.

So back to the test version, all times to 10 seconds, all ok. 
I just set  battery report(20) and no more battery report.

After some test, debug and reverse I notice that in case of sleeping nodes, the timer elapsed time was estimated based on the nodemanager sleeping time. This is a good idea but the implementation is complex.
In the original nodemanager implementation this was done by the timer update function called by the Sensor::loop. Then the elapsed time was available in the timer. This is working but require to call the update function for each timer and in case of sensors local timers can be annoying.

In the architecture_review version, the update method is no more present. The elapsed time is directly computed in the Timer::getElapsed() method. This is the problem. 
The Timer::getElapsed() method can be invoked several time in a loop, so if we cumulate a sleep time at each call the result is wrong. 
Maybe to avoid that, the function just return the sleep time, this is also wrong. We can run for several loops but the elapsed time still equal to sleep time.

So a local memory for the elapsed time with an update method to manage it is required.

Now in order to avoid the annoying problem of calling the update method for each timer used in the system, my proposal is to register all the timers in nodemanager and manage the timer update feature from the nodemanager core. The consequence of this approach is that the elapsed time, for each timer, is evaluated at the beginning of nodemanager loop and is stable during a loop. This change a little the behavior but ensure that several calls of isOver during the same loop give the same result (standard programming way for PLC) and allow the use of sleep time approach for sleeping nodes.

In order to achieve this :

On Timer class:
•	Timer::update() mothod added
•	Timer::getElapsed() go private
•	Long elapsedTime property added
•	Timer constructor register itself to nodemanager

On nodemanager class:
•	List of registered Timers added
•	registerTimer method added
•	at beginning of loop() method the update method of each registered timer is called


All the rest remain unchanged.

I tested that on my node with 10 seconds 20 seconds a 6 hours configuration. All ok for now. The node still under test.

Timer class code :
Timer.h
```diff
public:
        void stop();
        // return true if the time is over
        bool isOver();
-       // return elapsed time in seconds
-       long getElapsed();
+       // required to evaluate timer. 
+       // This ensure that multiple calls of isOver(); return the same value
+       // and manage special case for sleeping node
+       void update();
 private:
        timer_mode _mode = NOT_CONFIGURED;
        int _value = 0;
        bool _is_running = false;
        long _last = 0;
+       int _elapsed = 0;
 #if NODEMANAGER_TIME == ON
        bool _already_reported = false;
 #endif
+       // return elapsed time in seconds
+       long getElapsed();
 };

 #endif
```

Timer.cpp
```diff
#include "Timer.h"

 Timer::Timer() {
+       nodeManager.registerTimer(this);
 }

void Timer::start() {
	_is_running = true;
#if NODEMANAGER_TIME == ON
	// save the current timestamp (which is sync'ed when sleeping or not sleeping)
	if (_mode == TIME_INTERVAL) _last = now();
	// keep track of the current minute/hour/day
	if (_mode == EVERY_MINUTE) _last = minute();
	if (_mode == EVERY_HOUR) _last = hour();
	if (_mode == EVERY_DAY) _last = day();
 #else
        // keep track of millis() for calculating the difference
        _last = millis();
+       _elapsed = 0;
 #endif
 }


+// return elapsed seconds so far
+long Timer::getElapsed() {
+       return _elapsed;
+}
+

-// return elapsed seconds so far
-long Timer::getElapsed() {
+void Timer::update() {
        // calculate the elapsed time
-       long elapsed = 0;
 #if NODEMANAGER_TIME == ON
        // system time is available so use now() to calculated the elapsed time
-       elapsed = (long)(now() - _last);
+       _elapsed = (long)(now() - _last);
 #else
        // system time is not available
 #if NODEMANAGER_SLEEP == ON
        // millis() is not reliable while sleeping so calculate how long a sleep cycle would last in seconds and update the elapsed time
-       if (nodeManager.isSleepingNode()) elapsed += nodeManager.getSleepSeconds();
+       if (nodeManager.isSleepingNode()) _elapsed += nodeManager.getSleepSeconds();
 #endif
        // use millis() to calculate the elapsed time in seconds
-       if (! nodeManager.isSleepingNode()) elapsed = (long)((millis() - _last)/1000);
+       if (! nodeManager.isSleepingNode()) _elapsed = (long)((millis() - _last)/1000);
 #endif
-       return elapsed;
-}
```

NodeManager class code :
**NodeManager.h**
```diff
public:
        void sendMessage(int child_id, int type, const char* value);
        // register a sensor
        void registerSensor(Sensor* sensor);
+       // register a timer
+       void registerTimer(Timer* timer);
        // return the next-available child id
        int getAvailableChildId(int child_id = -255);
        // list containing all the registered sensors
        Child* getChild(int child_id);
        // return the sensor object of the given child_id
        Sensor* getSensorWithChild(int child_id);
#if NODEMANAGER_SLEEP == ON
        // [3] set the duration (in seconds) of a sleep cycle
        void setSleepSeconds(int value);
private:
        bool _sleep_or_wait = true;
        int _sleep_interrupt_pin = -1;
        int _sleep_between_send = 0;
        void _sleepBetweenSend();
        int _report_interval_seconds = 10*60;
        int _reboot_pin = -1;
        void _present(int child_id, int type);
        bool _sync_time_after_sleep = true;
        unsigned int _sync_time_after_interval = 0;
 #endif
+       List<Timer*> timers;
 };

 #endif
```

**NodeManager.cpp**
```diff
void NodeManager::registerSensor(Sensor* sensor) {
        sensors.push(sensor);
 }

+void NodeManager::registerTimer(Timer* timer) {
+       timers.push(timer);
+}
+
void NodeManager::loop() {
#if NODEMANAGER_TIME == ON
	// if the time was last updated more than the given number of minutes ago, update it
	if (_time_is_valid && _sync_time_after_interval > 0 && (now() - _time_last_sync) > (long)_sync_time_after_interval*60) syncTime();
#endif
#if NODEMANAGER_POWER_MANAGER == ON
        // turn on the pin powering all the sensors
        powerOn();
 #endif
+
+       // run loop for all the registered timers in order to update
+       for (List<Timer*>::iterator itr = timers.begin(); itr != timers.end(); ++itr) {
+               Timer* timer = *itr;
+               timer->update();
+       }
+
        // run loop for all the registered sensors
        for (List<Sensor*>::iterator itr = sensors.begin(); itr != sensors.end(); ++itr) {
                Sensor* sensor = *itr;
```

Hope that can help.

**Comment by user2684** [comment]
@Akubi thank you sooooo much for the excellent and detailed explanation. You are 100% right, when I removed update() from Timer I wondered "why did I add at first this useless method?!?". Here's the reason! :-) So yes, that one has to be back. Regarding your implementation with the NodeManager class managing the timers, I think it is lovely. Only concern is if with so many timers the List class could cause memory issues but this is a different problem. I'll be out for a few days and do some tests with your recommended solution once back. Thanks again for the valuable contribution!

**Comment by Akubi** [comment]
Hi @user2684,

I was also out for a long WE. Just back. Happy if that can help, but the big contribution to the MySensors community is your NodeManager.
If any question or if you want a copy of my source code, don’t hesitate.

I’m actually working on 2 aspects :

- EEPROM, some issues, but not big problem
- Battery Powered Sensor, here more tricky

For Battery Powered Sensor, the major point is sleepBetweenSend() method. In fact I have some issue with.
But the first question is: What is the purpose of this function ? My feeling is that can help, and that help, getting the radio capacitor back after a send. But pushing the sensor in sleep mode will produce Ack answer errors in case of messages requiring Ack (example presentation) and the sensor will retry. Finally the sensor use more power.

So I still have to analyze a bit better the situation but if you have some time when back to discuss the purpose of this function, that can certainly help me .

**Comment by knopserl** [comment]
@Akubi I'm also very interested in the battery powered sensor and deep sleep (of the ESP32 MCU). It switches off almost everything including CPU, sensors ,RFM transceicer and it does a warm restart (running thru the setup routine) and need to initialize and re-initialize the peripherals. The only thing you can save (with the ESP CPU) is 8k RTC memory and you get the restart reason (e.g. timer wakeup/restart).

**Comment by Akubi** [comment]
@user2684,
Sorry but I have a problem with timers. 
In fact, for my battery nodes, I'm trying to set the setForceUpdateTimerValue to 1 day. Problem the _value is and int representing seconds. So 1 day = 86400 sec. Not ok for an int.

If i take a look to the timer structure we have :

```
int _value = 0;          // sec    (max 9 hours)
long _last = 0;          // msec   (max 24 days)
int _elapsed = 0;        // sec    (max 9 hours)
```

So this is a problem. 
First we can use unsigned int and unsigned long in order to get 1 more bit. But the result is 18 hours for unsigned int and 49 days unsigned long.
Is better but still not working for 1 day. And even the setReportIntervalDays(int value) method is useless.

OK we can change _value and _elapsed to unsigned long, but this will affect one more time the code and RAM usage for timers.
Any other idea ?

**Comment by Akubi** [comment]
@user2684,
Hi, I mabye found a way to manage the problems. I need some more days to test and then I will send you a revised version as proposal. Hope you can find some time to review my proposal and make comments.

**Comment by user2684** [comment]
@Akubi on the EEPROM issue, it should be solved with commit 981308c. The problem was a bit more complex actually and two issues were there. One was as you pointed out with reset() and the other was with _value_processing.  _value_processing default is AVG (which fit any sensor taking measures) so DigitalOutput was averaging the values messing up everything. I added setValueProcessing(NONE) to DigitalOutput (and all the other actuators) so only the last value set is retained. As for reset(), resetting the counters is required by any sensor which is taking a measure and start over after reporting so that piace of code has to stay there. BUT when value processing is NONE, there is nothing to do with the counters so that code is not executed. I tested it out and seems to work, let me know if works on your side as well. Looking at the other issues now. Thanks!

**Comment by user2684** [comment]
@Akubi sorry for spamming first of all. As for the timer issue, I've implemented your recommendation in 7405c13. I'm still not fully convinced it can scale due to the way List is implemented (e.g. with too many push could cause memory issue). But I couldn't find an alternative implementation: the only place where this update can take place is in NodeManager::loop() and there are too many timers around to ask Sensor to update them consistently. We would need to test this a bit to be sure fixing one problem has not introduced another. Btw, this makes me realize v1.7 implementation was buggy as well, since too many timers were not updated consistently (e.g. the safeguard timer of DigitalOutput). Big finding, thanks.

I've also renamed NodeManager.h and cpp file in Node.h and cpp to avoid the conflict you mentioned. Moving on to the next issue :P

**Comment by user2684** [comment]
@Akubi getting to your last finding about setForceUpdateTimerValue. Heck you are fully right. I see two alternatives, going to the unsigned long way with an implicit upper bound or adding an additional variable just to keep track of the days. Probably the first is best but I agree with the concerns regarding memory utilization since there are many timers the problem tends to be bigger. Let me know if you found a better approach, otherwise I'll go with this solution. Thanks!

**Comment by Akubi** [comment]
@user2684, I set up a proposal for solving the timer issue based on unsigned long. Of course memory usage can be an issue. In order to address this I changed memory layout of the NodeManager itself.
So my proposal is based on  a copy of August 6. So your last changes are not included.
If you agree with my changes some merge are probably required.
I'm out for the WE, so I send you a copy of my proposal in attach.
Hope that can help and don’t hesitate to ask if any question.


[NodeManager-feature-architecture_review v1.8-Dev3.zip](https://github.com/mysensors/NodeManager/files/2384997/NodeManager-feature-architecture_review.v1.8-Dev3.zip)

**Comment by Akubi** [comment]
@user2684, I'm back from my WE. Do you already take a first look to my proposal ?
Just to know if I can continue in that way.
I yes I can merge your last modification and send you a consolidated version.
I know, available time is limited. Don't worry if you don't have time now

**Comment by Akubi** [comment]
@user2684, your are welcome.
I received some hardware components so this week I will be busy assembling nodes, but please don't hesitate, if I can help in evolving this nice toll  that will be a pleasure.
If you have items in the to do list or need help for testing just ask.

**Comment by user2684** [comment]
@Akubi finally done with the data refactoring, I took a while since has to be done mostly manually. Now this PR and your version should be mostly aligned since included also your changes to sleepBetweenSend, the order in the constants and string support in ConfigurationRequest. Plus this PR already included the most robust logic of the timers implemented a while back. The only things missing are your changes to SensorACS712 and Diplay5110 which would probably better to go through dedicated PRs (once this will be merged). I'll check all of those changes in the next few days so to be sure there is no wrong copy and paste from my side. 
One question for your regarding the changes in ConfigurationRequest. Is `char _string_data[MAX_PAYLOAD+1];` going to use a huge amount of storage? It doesn't seem so in my test but wonder if I'm just missing something. Thanks

**Comment by Akubi** [comment]
@user2684, Thank for feedback and for taking in account my proposals.
Concerning SensorACS712 and Diplay5110, yes I agree. Separate PRs.
Concerning ConfigurationRequest, sorry for a mistake, correct declaration for getFunction is :
	// return the parsed function
	uint8_t getFunction();
Now, the `char _string_data[MAX_PAYLOAD+1];` storage usage is 26 bytes. I set this buffer to MAX_PAYLOAD+1 in order to avoid buffer overrun problems.
Of course storage usage must be checked at runtime. This is a member of ConfigurationRequest class and ConfigurationRequest is localy declared in onReceive method of SensorConfiguration class. So the memory is allocated on stack. Not easy to check. I run my memory analysis tool and yes memory is allocated.
I will study if I can integrate in the future the memory analysis system in the debug function of NodeManaged, but this is another story.

**Comment by user2684** [comment]
After doing some tests I've noticed a few issues especially with timers and sensors not supposed to report periodically (e.g. relays): since _samples was not updated, value was never reported. Fixed it together with a few other minor things. I'm going now to merge this PR since seems kind of working and don't want to stop other PRs to get in. Maybe we can plan a sort of review of this later on, for sure before releasing v1.8.
I've also updated the description with the new things and referenced specific issues for the most relevant changes. Thanks again @Akubi for such valuable contributions!

**Comment by user2684** [comment]
And regarding memory utilization monitoring, would be great if we can take this somehow into consideration, maybe in a different PR/release. There is too much floating on the stack, the risk something goes wrong with the memory continuously increases :-)

**Comment by Akubi** [comment]
@user2684, perfect thank. I'm also doing some test and found troubles with CONDITIONAL_REPORT.
But no problems we can now go with specifics PRs

**Comment by user2684** [comment]
@Akubi FYI, regarding memory utilization, I've just added something very basic to start with in #408 using the built-in function already provided by the MySensors library, just to have a starting point.

**Comment by Akubi** [comment]
@user2684 OK perfect thank.
I will take a look as soon as possible.
At the moment I'm facing some problems with MySensors 2.3.0
I'm not able to start on a 1MHk node. No parent identification.

**Pull request merged**
