### PR TITLE
Make smart sleep optional

### PR DESCRIPTION
**Pull request by liwenyip**
Addresses #258

### CODE REVIEW

**Comment by user2684** [comment]
Hi, I'd prefer to use FEATURE_* only for consistent feature with the primary objective to save storage when needed. For this reason if ok for you I'd ask to create a boolean _smart_sleep variable and allow the user to change it pro grammatically instead of using the preprocessor. Thanks!

**Comment by liwenyip** [comment]
Sure thing. I assume you mean a member variable with a getter and setter?

**Comment by user2684** [comment]
Sorry, I meant a private variable of the NodeManager's class, not a global variable, and a setter method to change the default behavior (which should be true). I think we can afford just an additional boolean variable in terms of storage utilization. Thanks!

**Comment by user2684** [comment]
Closing since already fixed through #305

**Pull request closed without merging**
